### ISSUE TITLE
Metrics endpoint returns 500

### ISSUE THREAD

**Issue by findmyname666** [knyar/phalerts#8] opened 2022-09-08 13:24 UTC
I was testing the service but `/metrics` endpoint doesn't work in my case for some reason:

```
# curl -vvv http://127.0.0.1:8293/metrics
* Expire in 0 ms for 6 (transfer 0x559a8c0b80f0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559a8c0b80f0)
* Connected to 127.0.0.1 (127.0.0.1) port 8293 (#0)
> GET /metrics HTTP/1.1
> Host: 127.0.0.1:8293
> User-Agent: curl/7.64.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 INTERNAL SERVER ERROR
< Content-Type: text/html; charset=utf-8
< Content-Length: 290
< Server: Werkzeug/1.0.1 Python/3.8.8
< Date: Thu, 08 Sep 2022 13:22:50 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Could you verify it once you have time pls ?

Thx

**Comment by knyar** [comment] 2022-09-10 09:58
I've just checked my running instance and `/metrics` endpoint seems to be working correctly. I am using slightly older version of dependencies (`Werkzeug/0.12.2 Python/3.5.3`).

Do you see anything in the logs that could help identify what the issue is?

**Comment by zloo** [comment] 2023-01-09 17:25
This is probably caused by:
```
phalerts.py[975]:     resp = make_response(prometheus.generate_latest(prometheus.core.REGISTRY))
phalerts.py[975]: AttributeError: module 'prometheus_client' has no attribute 'core'
```

I'm pretty sure it could be easily fixed by just removing the `core` part and doing this:
```
resp = make_response(prometheus.generate_latest(prometheus.REGISTRY))
```

on this line: https://github.com/knyar/phalerts/blob/master/phalerts.py#L254

Not sure if this was some change in some version of the prometheus client library. You might need to specify a version requirement for this change if it does not work on some older version. I tested 0.8.0 and 0.15.0 and it works fine on both.

**Closed as completed** 2023-01-09 18:17 UTC
